# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ebb82781f8e7046354ffb74d93464388545a7aca52a58fd743c9f66105559e3a31e9f9d11e739e331de0b48abd4e0f2d19bc32a81f9bb1f64cb760aa717d6c8

test:
  secret_key_base: e9e39e8f2fe3460e1ef22f8fc5a90e992c62f9314b66151254c2e220c6a0a8aaa9726732f9d8303cdbc9e00211bfa44de5f340af6489bf294d587b971926c681

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
